name: Auto-add to Project on "use story" Label

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue or PR has the "use story" label
        if: contains(github.event.label.name, 'use story')
        run: echo "Label 'use story' found, proceeding with action."

      - name: Set up GitHub CLI
        run: |
          sudo apt-get install -y gh
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Add issue or PR to Project using GitHub CLI
        run: |
          gh issue set-project ${{ github.event.issue.number || github.event.pull_request.number }} \
          --project "https://github.com/users/MrSalim86/projects/1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
