name: Auto-add to Project on "use story" Label

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue or PR has the "use story" label
        if: contains(github.event.label.name, 'use story')
        run: echo "Label 'use story' found, proceeding with action."

      - name: Add issue or PR to project
        uses: actions/add-to-project@v0.1.0
        with:
          project-url: 'https://github.com/users/MrSalim86/projects/1'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          content-id: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
